language: c
cache: ccache

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - gettext
    - intltool
    - valgrind

script:
  - ./autogen.sh && ./configure && make
