language: c
cache: ccache

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - gettext
    - intltool
    - valgrind
    - libgtk2.0-dev
    - libotr2-dev

script:
  - ./autogen.sh && ./configure && make
